### ISSUE TITLE
deepsqueak !

### ISSUE THREAD

**Issue by bmacagno** [osimon81/SqueakR#5]
Hi Simon!

I am happy I stumbled across your code, I am also an undergrad and I am finishing up a project on isolation induced USVs in mouse pups. This is more of a DeepSqueak user related question. 

I see that SqueakR is able to visualize data based on the custom label. I was wondering if you could share how you have categorized vocalizations for your experiments. I have some large data sets and I do not have time to custom label by hand to train a supervised classifier, so I am thinking of using the unsupervised clustering method. 

I know this question isn't directly related to SqueakR but any advice you are willing to lend would be appreciated :)

Bea Macagno
Department of Psychology
Western Washington University

**Comment by osimon81** [comment]
Hi Bea! Thanks for your comment – apologies on the late response and I'm glad you were able to take a look at SqueakR! I'd say it depends on what you're looking at. There's work in rats that suggest that [frequency of vocalizations correlate with the animal's affect](https://www.frontiersin.org/articles/10.3389/fnbeh.2021.812142/full), so I'd guess in rats it'd be helpful to perform unsupervised clustering based on frequency first. For mice, I'm less sure whether there are direct connections to affect, but it's still a popular way to classify vocalizations.

I believe DeepSqueak gives the option of classifying vocalizations also based on the duration of each vocalization in the spectrogram, which also tends to separate out distinct calls pretty well. But you can definitely reach out to the DeepSqueak developers to follow up on what other types of analysis is common here.

The DeepSqueak wiki also references how to carry out [unsupervised clustering](https://github.com/DrCoffey/DeepSqueak/wiki/unsupervised-clustering) using the platform, so I'd check out this link for how to actually accomplish this. Hope this helps, and feel free to send me an email if you'd like any other clarifications or tips!
